### ISSUE TITLE
Part 3 Review

### ISSUE THREAD

**Issue by lmlariscy98** [okichris90/Cavros-and-Okitondo-MADA-Project#1]
This is a really interesting data set and I'm definitely interested to see what you find. All of the scripts ran with no problems and I was able to get everything to render properly. I liked your use of the table1 function in the descriptive analysis and I will definitely be trying that. For your statistical analysis file, I found it confusing and think it may make more sense to separate out the different model fits rather than work with many models at once, but if it works for you then I don't think it matters too much. One last note is I would definitely include more exploratory figures in your manuscript, I really liked those and thought they were very informative yet simple.

Score = 3

**Comment by okichris90** [comment]
Thank you for your feedback.
