### ISSUE TITLE
Part 3 feedback

### ISSUE THREAD

**Issue by SarBen811** [okichris90/Cavros-and-Okitondo-MADA-Project#2]
Good job! I have a few comments below, but overall a great job!
Grade = 3/3

Notes:
- All readme.md files are updated.
- Manuscript rendered properly.
- The model summaries look good on the manuscript, but maybe add some commentary on what the results are indicating. If you can add any of the exploratory figures into the manuscript without taking up too much space, I think it could help visually display the summary.
- All code files rendered correctly.
- I really liked the summary you had at the beginning of the stat analysis page. I might borrow that!
- I would also recommend adding a few more comments on the code pages on to explain what you are doing and what the results mean.

**Comment by okichris90** [comment]
Thank you for your feedback.
