### ISSUE TITLE
MADA Project Review

### ISSUE THREAD

**Issue by ghost** [okichris90/Cavros-and-Okitondo-MADA-Project#3]
Hello Chris and Irene, I have been assigned to review part 3 of your MADA course project so I will do my best to provide meaningful feedback. The following are comments I have regarding your project.  

1. Initially when opening your project, I first noticed that it is well organized, which I appreciate as a reader with no prior knowledge of your project. In addition, the first README file in the main project folder does a great job introducing the reader to the folders and files they will see, allowing them to comprehend how to reproduce your project. One suggestion is to add a very brief introduction/summary for your research focus/question in the first README file, so the reader immediately has some familiarity with what they are working with. I credit this idea to Nicole Luisi, who commented this on my project.  

2. I wanted to point out that I had no problem running the code in your project and it was quite easy to follow along due to the relevant README files and annotations. If you keep annotating and updating the README files, I think you guys are going to have an easily reproducible project, great job.  
 
3. The only other comment I am going to make is that I think it is important for your project to have a completed “code and file information” section of the supplementary material and file. I realized how helpful this section is when I reviewed Amelia Foley’s MADA project (which can be found in the “Course Project Example” section of the MADA course website). If either of you get a chance, I recommend checking Amelia’s supplementary material section as she lists out every file with a brief description. This helps the reader navigate the project and use it as a reference.   

Overall, you two have an organized and up-to-date project that I struggled to comment on because of how reproducible the project currently is. Great job so far and I am excited to see where this project goes. 

Grade: 3/3

**Comment by okichris90** [comment]
Thank you so much for this feedback, Jacob!
